language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- pypy2.7-5.8.0
- pypy3

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.7-dev
install:
  - pip install tox
  - python setup.py bdist_wheel
  - pip install --use-wheel ./dist/vulture-*.whl
script:
  # Run the installed version of vulture on local code.
  - vulture vulture/ tests/
  - tox -e cleanup,py,docs
  # flake8 doesn't support Python 2.6
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then tox -e style; fi
