name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [pypy3, 3.6, 3.7, 3.8]
        os: [macos-10.15, ubuntu-18.04, ubuntu-20.04, windows-2019]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade coveralls setuptools tox wheel

    - name: Build wheel
      run: python setup.py bdist_wheel

    - name: Install Vulture from wheel (For Linux and MacOS)
      if: ${{ matrix.os != 'windows-2019' }}
      run: "python -m pip install --only-binary=:all: ./dist/vulture-*.whl"

    - name: Install Vulture from wheel (For Windows)
      if: ${{ matrix.os == 'windows-2019' }}
      run: "python -m pip install --only-binary=:all: --ignore-installed --find-links=dist/ vulture"

    - name: Run Vulture
      run: |
        vulture vulture/ tests/
        python -m vulture vulture/ tests/

    - name: Run Tests
      run: python -m tox -e py

    - name: Check for Style Issues
      if: ${{ matrix.python-version == 3.6 && matrix.os == 'ubuntu-18.04' }}
      run: python -m tox -e style
